version: '3.4'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=crynotes
      - POSTGRES_PASSWORD=123qwerty
      - POSTGRES_USER=crynotes
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  
  api:
    build:
      context: ../BackendApp/CryNotes.Api
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
#      - DOTNET_USE_POLLING_FILE_WATCHER=1
    depends_on: 
      - db
    ports:
      - 5000:5000
 
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  db-data: {}