version: '3.4'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=crynotes
      - POSTGRES_PASSWORD=123qwerty
      - POSTGRES_USER=crynotes
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  
  api:
    build:
      context: ../BackendApp/CryNotes.Api
      target: final
    depends_on: 
      - db

volumes:
  db-data: {}